version: "2"

services:
  django:
    env_file:
     - develop.env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - "8080:8080"
    networks:
     - django-network
    command: ["/usr/bin/uwsgi", "--ini", "/var/www/uwsgi.ini"]
    volumes:
      - "/home/wolle/projects/django1:/var/www"

  postgres:
    env_file:
     - develop.env
    image: postgres
    networks:
     - django-network
    ports:
    - "5432:5432"
    volumes:
    - db-data:/var/lib/postgresql/data

networks:
  django-network:
    driver: bridge
