version: '3.7'

services:
  django:
    env_file:
     - develop.env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - "8000:8000"
    networks:
     - django-network
    command: ["/usr/bin/uwsgi", "--ini", "/var/www/uwsgi.ini"]
    volumes:
      - type: volume
        source: mydata
        target: /var/www
        volume:
          nocopy: true

  postgres:
    env_file:
     - develop.env
    image: postgres
    networks:
     - django-network

  ubuntu:
    env_file:
      - ubuntu.env
    image: ubuntu:latest
    command: /bin/bash

networks:
  django-network:
    driver: bridge

volumes:
  mydata: /home/wolle/projects/django1
